storage.yml
------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer


pvc.yml
---------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi


pod.yml
----------
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim

To describe the YAML resources before deletion, you can use the `kubectl describe` command. Here are the commands:

1. **Describe the Pod:**
   kubectl describe pod app
   
2. **Describe the PersistentVolumeClaim (PVC):**
   kubectl describe pvc ebs-claim
 
3. **Describe the StorageClass:**
   kubectl describe storageclass ebs-sc

kubectl get pods
kubectl get pvc
kubectl get storageclasses
kubectl delete pod app
kubectl delete pvc ebs-claim
kubectl delete storageclass ebs-sc
