storage.yml
---------------
   apiVersion: storage.k8s.io/v1
   kind: StorageClass
   metadata:
     name: ebs-sc
   provisioner: ebs.csi.aws.com
   parameters:
     type: gp2
   volumeBindingMode: WaitForFirstConsumer
   allowVolumeExpansion: true
   
chanPVC.yml
---------------
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: ebs-claim-changable
     annotations:
       volume.beta.kubernetes.io/storage-class: "ebs-sc"
   spec:
     accessModes:
       - ReadWriteOnce
     storageClassName: ebs-sc
     resources:
       requests:
         storage: 2Gi
pod.yml
---------
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim-changable

 
 
 
 Kubernetes natively supports increasing the size of a PersistentVolumeClaim (PVC), but it does not support decreasing the size
