apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod-1
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'Pod IP: $(hostname -i)' > /cache/pod_ip.txt ; date > /cache/date.txt ; sleep 1000"]
    volumeMounts:
    - mountPath: /cache
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod-2
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'Pod IP: $(hostname -i)' > /cache/pod_ip.txt ; date > /cache/date.txt ; sleep 1000"]
    volumeMounts:
    - mountPath: /cache
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp
      type: DirectoryOrCreate
